Data downloader
labdac/charlacompling pull request #3
Opened 2018-12-02 07:56 UTC by CrossNox

Agrego un par de clases para descargar los datasets que estoy usando

2018-12-03 18:24 UTC, Roj approved these changes

2018-12-04 13:39 UTC, Roj requested changes

2018-12-04 13:39 UTC, Roj commented on data/corpus_downloaders.py
> +    def __init__(self, lang, grive_id):
grive_id => gdrive_id

2018-12-04 13:39 UTC, Roj commented on data/corpus_downloaders.py
> +        os.makedirs(os.path.join(*path.split(os.path.sep)[:-1]), exist_ok=True)
Me está dando este error:
```
🐮 python3 corpus_downloaders.py
Traceback (most recent call last):
  File "corpus_downloaders.py", line 96, in <module>
    WikipediaEnDumpDownloader().download("/tmp").extract("/tmp")
  File "corpus_downloaders.py", line 34, in download
    os.makedirs(os.path.join(*path.split(os.path.sep)[:-1]), exist_ok=True)
TypeError: join() missing 1 required positional argument: 'a'
```
cuando lo corro así:
```
if __name__ == "__main__":
     WikipediaEnDumpDownloader().download("/tmp/").extract("/tmp/")
```
y encontré [este comentario](https://github.com/borgbackup/borg/issues/3388#issuecomment-347059394) relacionado

2018-12-27 06:28 UTC, CrossNox commented
@jorgeCollinet @Roj  good to merge?

2018-12-27 15:33 UTC, jorgeCollinetNavent commented
le estoy cambiando boludeces
no encuentro la linea nltk.download(´stopwords´), se agrego en algun lado?

2018-12-28 05:13 UTC, CrossNox commented
@jorgeCollinet done

2018-12-28 05:39 UTC, jorgeCollinet commented
estoy probando un poco de mejora de performance en Word2Vec_BWC:

nose si conviene primero mergear lo que ya esta, y después trabajar con lo siguiete:

1) pasar de utils las listas de stopwords y nonworrds a sets así ver si una palabra es stopword es O(1)
2) estoy probando una versión experimental que usa varios procesos para leer los archivos y pasárselo al gensim

2018-12-28 05:45 UTC, CrossNox commented
La 1, go for it, no es tanto laburo. La 2 me genera intriga, por los siguientes factores:
-  GIL
- Gensim no creo que pueda recibir de a mas de un proceso por vez
- El parametro `workers` no tiene ningun efecto en la construcción de las frecuencias?
Sí la respuesta a esto último es no, quizás antes que pasarle a gensim, habría que armar el diccionario de frecuencias con varios procesos y pasarle eso

2018-12-28 05:55 UTC, jorgeCollinet commented
Correcto, el gensim no recibe más de un proceso a la vez
Pero lo que tarda es la función de preprocesamiento.

No tengo idea si los workers influyen en el modelo, mepa que no deberían.

Igual me parece que mejor hagamos merge de estoy a máster y después subo la posible optimización.

un saludo

El 28 dic. 2018 2:45, CrossNox <notifications@github.com> escribió:

La 1, go for it, no es tanto laburo. La 2 me genera intriga, por los siguientes factores:

  *   GIL
  *   Gensim no creo que pueda recibir de a mas de un proceso por vez
  *   El parametro workers no tiene ningun efecto en la construcción de las frecuencias?
Sí la respuesta a esto último es no, quizás antes que pasarle a gensim, habría que armar el diccionario de frecuencias con varios procesos y pasarle eso

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/labdac/charlacompling/pull/3#issuecomment-450294529>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AHMDFhYkn4h3VhcdGgM-pjK5k3PgSMQhks5u9a_0gaJpZM4Y9SiE>.

2018-12-28 18:45 UTC, merged